### ISSUE TITLE
Unable to access app-store submitted app documents

### ISSUE THREAD

**Issue by robm92** [emonti/afcclient#3]
Using:
`afcclient -u [UDID] -a [BundleID] list`

Only works for non-app-store submitted apps.

Error:

> Error: house_arrest service responded: InstallationLookupFailed

Tested on iPad 4th Gen, ipad mini 4th Gen. MacOS Sierra and El Capitan

**Comment by emonti** [comment]
As of recent iOS versions (8+ i believe) apple locked down the house-arrest
service so that it only allows access to app-store upplications that have
enabled backups in their Info.plist.

**Comment by emonti** [comment]
Since this is the expected behavior on newer iOS versions, I am going to close this issue.

**Comment by robm92** [comment]
I have tested on a store submitted app with `Application supports iTunes file sharing` set to YES and am still experiencing the issue. I understand access is now restricted only to the /Documents directory however the following does not work:
`afcclient -u [UDID] -a [BundleID] list /Documents`
I can confirm that documents are visible through iTunes however.

**Comment by robm92** [comment]
Can confirm that fixes it. Excellent, thank you!

**Comment by emonti** [comment]
Thanks for the follow-up @eriksmets and @robm92 - could you see if the commit below makes it work when you add the --documents/-d command-line opt?

This way afcclient can retain support container access on older iOS versions as well.

eb3ab3e06cb4538d1d82c723cda837bd71c6fe62

**Comment by robm92** [comment]
Tested working fine with a store app:
`./afcclient -a [bundleID] -d -u [UDID] info Documents`
And as expected the following will not work as it is trying to access the container instead of just Documents:
`./afcclient -a [bundleID] -u [UDID] info Documents`

However this works fine when accessing an Xcode signed app.

Thanks again guys, really helpful!

**Comment by emonti** [comment]
ok if i close this issue again?

**Comment by eriksmets** [comment]
Yeah, it works fine. The issue can be closed 😊

**Comment by emonti** [comment]
Cheers!
