### ISSUE TITLE
Transfer failed: MUX_ERROR

### ISSUE THREAD

**Issue by eriksmets** [emonti/afcclient#5]
Using afcclient to upload large files to the Documents folder of an app results in a failed transfer and 'MUX_ERROR', when doing this over Wi-Fi. Using USB, everything works.

I don't really know what the problem is. Is it the iDevice going to (deep) sleep ? Is it a network connection loss that it can't recover from/ doesn't retry sending the packet.. ?

Do you think there could be some keepalive or error-retry function added ?

**Comment by emonti** [comment]
I've not really tested afcclient with Wi-Fi at all TBH, and I'm not remotely familiar with the setup at all or how it's implemented in libimobiledevice, sorry. In short, only USB mode was intended to be supported, YMMV with Wi-Fi.

But, out of curiosity, have you tried the same thing using something like ifuse which also uses libimobiledevice? Does it behave better?
