### ISSUE TITLE
make not working

### ISSUE THREAD

**Issue by TheLastLovemark** [emonti/afcclient#7]
Hi,

I run macports, so I had to install _libimobiledevice_ to `/opt/local/` to avoid conflicts. Nothing should be installed to `/usr/local/bin`.

I have MP set to use clang 4 (mp-clang-4.0) and set the `CC` environmental variable to `clang-mp-4.0`, which is located in `opt/local/bin` (_I'm aware of the syntax mismatch_). `CFLAGS` is set to `'-O2 -arch x86_64 -arch ppc64 -arch i386 -arch ppc'`.

_I am pretty sure this version of clang supports blocks._

When I try to compile _afcclient,_ as root, I get the following:

`sh-3.2# pwd`
`/users/<login_account>/afcclient-master`
`sh-3.2# make`
`clang    -c -o afcclient.o afcclient.c`
`In file included from afcclient.c:30:`
`./libidev.h:17:10: fatal error: 'libimobiledevice/libimobiledevice.h' file not found`
`#include <libimobiledevice/libimobiledevice.h>`

		`^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`1 error generated.`
`make: *** [afcclient.o] Error 1`

`sh-3.2# ls -fs /opt/local/include/libimobiledevice` reveals that the header file `libimobiledevice.h` **is installed as expected**.

Where did I go wrong?

Thank you for any help you can provide.

Best,

**Comment by userlandkernel** [comment]
There is a flaw in the code.

**Comment by emonti** [comment]
Try specifying LDFLAGS and CFLAGS when you run make, as follows:

    $ LDFLAGS="-L/opt/local/lib" CFLAGS="-I/opt/local/include" make
